### ISSUE TITLE
Getting stuck on `muffin new`

### ISSUE THREAD

**Issue by fa7ad** [muffinjs/cli#47]
I tried it a couple of times every time it outputs `undefined` and just freezes there.
![screenshot from 2016-05-18 08-39-45](https://cloud.githubusercontent.com/assets/7447677/15345836/5bbf2b72-1cd4-11e6-9dfe-0a471a8ac37c.png)
I know this isn't a mongo issue because I can log into mongo just fine
![screenshot from 2016-05-18 08-40-07](https://cloud.githubusercontent.com/assets/7447677/15345855/7077ad0a-1cd4-11e6-804f-715ac51d5853.png)

any ideas what could be the problem? I really wanna try this out

**Comment by leo** [comment]
Can you post your node version and the version of muffin? :blush: Really weird. Also: It looks like although your database password is "muffin" (which has 6 chars), there are more than 6 chars in the upper image for the DB password...

**Comment by fa7ad** [comment]
sorry wrong screencap. the password is "l33tpass"... which works fine.
![screenshot from 2016-05-19 03-51-32](https://cloud.githubusercontent.com/assets/7447677/15376175/30189a16-1d75-11e6-8639-bedbab0a3064.png)

Muffin is at version **0.2.0**
![screenshot from 2016-05-19 03-53-25](https://cloud.githubusercontent.com/assets/7447677/15376189/4d4473f8-1d75-11e6-81f1-5d69bcfab130.png)

**Comment by fa7ad** [comment]
And in case you wanna check the roles
![screenshot from 2016-05-19 04-07-23](https://cloud.githubusercontent.com/assets/7447677/15376531/4d855074-1d77-11e6-8110-742326fe07b5.png)

**Comment by leo** [comment]
@fa7ad Can you clone the master branch and try it again (please uninstall muffin-cli before that)? Should work fine now!

**Comment by fa7ad** [comment]
yeah the master branch worked, I had to manually create the collections though. and apparently i have to recreate users for each database before attempting to authenticate (according to StackOverflow) :frowning:

**Comment by fa7ad** [comment]
Also, I entered all the information (username/password) when `muffin new` asked for them, but now I have what looks like a blank templated **.env** file... _room for improvement? or bug?_
![screenshot from 2016-05-21 02-09-27](https://cloud.githubusercontent.com/assets/7447677/15440836/6ba43060-1ef9-11e6-868e-7386c3f326e8.png)

**Comment by leo** [comment]
Hehe... Yeah, I think the "creating users for each database" is just how MongoDB works.

Regarding the `.env` file: Yep, I haven't implemented that the command line utility changes the contents of the file on the fly before writing them to the destination folder. So yes, there's still room for improvement and I'm planning to add it soon. However, a PR is also welcomed :blush:

Closing this for now, since the main issue seems to be resolved.

**Comment by leo** [comment]
Just opened https://github.com/muffinjs/cli/issues/52

**Comment by leo** [comment]
Should be fixed on master. Will release it with the next minor version!

**Comment by fa7ad** [comment]
thanks, I was gonna take a look and maybe PR but, looks like you already fixed it :smile:
